# Generated by Django 4.0.7 on 2023-02-02 05:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract_relations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_length', models.DurationField(default=datetime.timedelta(days=183))),
                ('n_transactions', models.IntegerField()),
                ('avg_trx_freq', models.FloatField()),
                ('avg_gas_consumed', models.FloatField()),
                ('median_sender_nonce', models.FloatField()),
                ('returning_user_perc', models.FloatField()),
                ('n_unique_incoming_addresses', models.IntegerField()),
                ('n_deployer_transactions', models.IntegerField()),
                ('contains_abi', models.BooleanField()),
                ('trust_score', models.IntegerField(default=None, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_relations.contract')),
            ],
        ),
    ]
