# Generated by Django 4.0.6 on 2022-07-04 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1024)),
                ('github_repo', models.CharField(default=None, max_length=2048, null=True)),
                ('code_location_url', models.CharField(default=None, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, null=True)),
                ('website_url', models.CharField(default=None, max_length=1250, null=True)),
                ('github_url', models.CharField(default=None, max_length=1250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, null=True)),
                ('github_profile', models.CharField(default=None, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1024)),
                ('chain_name', models.CharField(default='Ethereum', max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_relations.person')),
            ],
        ),
        migrations.CreateModel(
            name='DAppAssociate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_type', models.CharField(max_length=120)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_relations.person')),
                ('dapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_relations.dapp')),
            ],
        ),
        migrations.CreateModel(
            name='ContractRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=120)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='contract_relations.contract')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='contract_relations.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_type', models.CharField(max_length=120)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_relations.contract')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_relations.person')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='dapp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_relations.dapp'),
        ),
    ]
