# Generated by Django 4.0.7 on 2023-02-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_relations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contract_name',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
