# Generated by Django 4.0.7 on 2023-02-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_relations', '0002_address_contract_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='contract_name',
        ),
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
