# Generated by Django 4.0.7 on 2023-02-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_relations', '0003_remove_address_contract_name_contract_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
